# Generated by Django 5.0.6 on 2026-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
    ]
